### ISSUE TITLE
Unable to have two form with Dropzone in the same page

### ISSUE THREAD

**Issue by bellu** [dachcom-digital/jquery-pimcore-formbuilder#1]
Hi, i have two different forms in one page with 2 different dropzone input.
Bui i'm getting this js error in the console:

`Uncaught Another dynamic multi file handler already has been defined. Only one handler allowed.`

Can i use only one form per page?

**Comment by solverat** [comment]
@bellu Nope, that's a bug and should be possible!

**Comment by solverat** [comment]
released in 1.0.1
